import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Link from "next/link";
import "./globals.css";
import styles from "./mainNav.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <nav className={styles.mainNav}>
          <Link href="/">
            <img src="/akudemy-logo.svg" alt="Akudemy Logo" style={{ height: 32, marginRight: 16, verticalAlign: 'middle' }} />
          </Link>
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/notifications">Notifications</Link>
          <Link href="/profile">Profile</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
